Controllers/ApoioController.cs
using Microsoft.AspNetCore.Mvc;

namespace RFB.Controllers
{
    public class ApoioController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "Novas linguagens de programação";
            return View();
        }
    }
}

Controllers/CnaesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RFB.Data;
using RFB.Models;
using Vereyon.Web;

namespace RFB.Controllers
{
    public class CnaesController : Controller
    {
        private readonly RFBContext _context;
        private readonly IFlashMessage _flashMessage;

        public CnaesController(RFBContext context, IFlashMessage flashMessage)
        {
            _context = context;
            _flashMessage = flashMessage;
        }

        // GET: Cnaes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cnae.ToListAsync());
        }

        // GET: Cnaes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cnae = await _context.Cnae
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (cnae == null)
            {
                return NotFound();
            }

            return View(cnae);
        }

        // GET: Cnaes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cnaes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Codigo,Descricao")] Cnae cnae)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(cnae);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    _flashMessage.Danger($"Erro: {ex.Message}");
                    return View(cnae);
                }
            }
            return View(cnae);
        }

        // GET: Cnaes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cnae = await _context.Cnae.FindAsync(id);
            if (cnae == null)
            {
                return NotFound();
            }
            return View(cnae);
        }

        // POST: Cnaes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Codigo,Descricao")] Cnae cnae)
        {
            if (id != cnae.Codigo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cnae);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CnaeExists(cnae.Codigo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cnae);
        }

        // GET: Cnaes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cnae = await _context.Cnae
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (cnae == null)
            {
                return NotFound();
            }

            return View(cnae);
        }

        // POST: Cnaes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var cnae = await _context.Cnae.FindAsync(id);
            if (cnae != null)
            {
                _context.Cnae.Remove(cnae);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CnaeExists(string id)
        {
            return _context.Cnae.Any(e => e.Codigo == id);
        }
    }
}

Controllers/NaturezasJuridicasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RFB.Data;
using RFB.Models;

namespace RFB.Controllers
{
    public class NaturezasJuridicasController : Controller
    {
        private readonly RFBContext _context;

        public NaturezasJuridicasController(RFBContext context)
        {
            _context = context;
        }

        // GET: NaturezasJuridicas
        public async Task<IActionResult> Index()
        {
            return View(await _context.NaturezasJuridicas.ToListAsync());
        }

        // GET: NaturezasJuridicas/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var naturezaJuridica = await _context.NaturezasJuridicas
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (naturezaJuridica == null)
            {
                return NotFound();
            }

            return View(naturezaJuridica);
        }

        // GET: NaturezasJuridicas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NaturezasJuridicas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Codigo,Descricao")] NaturezaJuridica naturezaJuridica)
        {
            if (ModelState.IsValid)
            {
                _context.Add(naturezaJuridica);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(naturezaJuridica);
        }

        // GET: NaturezasJuridicas/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var naturezaJuridica = await _context.NaturezasJuridicas.FindAsync(id);
            if (naturezaJuridica == null)
            {
                return NotFound();
            }
            return View(naturezaJuridica);
        }

        // POST: NaturezasJuridicas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Codigo,Descricao")] NaturezaJuridica naturezaJuridica)
        {
            if (id != naturezaJuridica.Codigo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(naturezaJuridica);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NaturezaJuridicaExists(naturezaJuridica.Codigo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(naturezaJuridica);
        }

        // GET: NaturezasJuridicas/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var naturezaJuridica = await _context.NaturezasJuridicas
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (naturezaJuridica == null)
            {
                return NotFound();
            }

            return View(naturezaJuridica);
        }

        // POST: NaturezasJuridicas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var naturezaJuridica = await _context.NaturezasJuridicas.FindAsync(id);
            if (naturezaJuridica != null)
            {
                _context.NaturezasJuridicas.Remove(naturezaJuridica);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NaturezaJuridicaExists(string id)
        {
            return _context.NaturezasJuridicas.Any(e => e.Codigo == id);
        }
    }
}

Controllers/QualificacoesSociosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RFB.Data;
using RFB.Models;

namespace RFB.Controllers
{
    public class QualificacoesSociosController : Controller
    {
        private readonly RFBContext _context;

        public QualificacoesSociosController(RFBContext context)
        {
            _context = context;
        }

        // GET: QualificacoesSocios
        public async Task<IActionResult> Index()
        {
            return View(await _context.QualificacoesSocios.ToListAsync());
        }

        // GET: QualificacoesSocios/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var qualificacaoSocio = await _context.QualificacoesSocios
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (qualificacaoSocio == null)
            {
                return NotFound();
            }

            return View(qualificacaoSocio);
        }

        // GET: QualificacoesSocios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: QualificacoesSocios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Codigo,Descricao")] QualificacaoSocio qualificacaoSocio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(qualificacaoSocio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(qualificacaoSocio);
        }

        // GET: QualificacoesSocios/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var qualificacaoSocio = await _context.QualificacoesSocios.FindAsync(id);
            if (qualificacaoSocio == null)
            {
                return NotFound();
            }
            return View(qualificacaoSocio);
        }

        // POST: QualificacoesSocios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Codigo,Descricao")] QualificacaoSocio qualificacaoSocio)
        {
            if (id != qualificacaoSocio.Codigo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(qualificacaoSocio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QualificacaoSocioExists(qualificacaoSocio.Codigo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(qualificacaoSocio);
        }

        // GET: QualificacoesSocios/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var qualificacaoSocio = await _context.QualificacoesSocios
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (qualificacaoSocio == null)
            {
                return NotFound();
            }

            return View(qualificacaoSocio);
        }

        // POST: QualificacoesSocios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var qualificacaoSocio = await _context.QualificacoesSocios.FindAsync(id);
            if (qualificacaoSocio != null)
            {
                _context.QualificacoesSocios.Remove(qualificacaoSocio);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QualificacaoSocioExists(string id)
        {
            return _context.QualificacoesSocios.Any(e => e.Codigo == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RFB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RFB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RFB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cnaes" asp-action="Index">Cnaes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NaturezasJuridicas" asp-action="Index">Naturezas Jurídicas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="QualificacoesSocios" asp-action="Index">Qualificações dos sócios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <flash dismissable="true" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RFB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_RodapeEspecial.cshtml
<div class="row">
    <div class="col-4">
        <p>Athon Ensino Superior</p>
    </div>
    <div class="col-4">
        <p>Sorocaba/SP</p>
    </div>
    <div class="col-4">
        <p>Curso de Engenharia</p>
    </div>
</div>

Views/Shared/_SemNavbar.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RFB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RFB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RFB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apoio" asp-action="Index">Apoio</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RFB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>